### PR TITLE
update index, script

### PR DESCRIPTION
**Pull request by kvchgtw**
章廷文
http://13.112.47.131:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Click arrow to scroll MRT list and click a MRT name, your page will load many unrelated attractions.
2. Search button does not align with search input vertically.

**Comment by kvchgtw** [comment]
@cwpeng Fixed the above-mentioned issues.

章廷文
http://13.112.47.131:3000/

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Comment by kvchgtw** [comment]
@cwpeng just requested a review from you, thanks!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
